const esc=s=>String(s||"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&apos;");
const reply=(s,code=200)=>new Response(`<?xml version="1.0"?><Response><Message>${esc(s)}</Message></Response>`,{status:code,headers:{"content-type":"application/xml","cache-control":"no-store"}});
const phone=s=>String(s||"").replace(/[^\d+]/g,""),now=()=>new Date().toISOString();
const slug=s=>String(s||"comic").normalize("NFKD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,70)||"comic";
const ext=t=>({"image/jpeg":"jpg","image/png":"png","image/gif":"gif","image/webp":"webp","image/heic":"heic","image/heif":"heif"}[t]||"bin");
const words=s=>{const a=String(s||"").split(/\r?\n/).map(x=>x.trim());return{title:a.shift()||"",caption:a.join("\n").trim()}};
const b64=b=>{let s="";for(const x of new Uint8Array(b))s+=String.fromCharCode(x);return btoa(s)};
async function signed(req,f,token){const sig=req.headers.get("x-twilio-signature");if(!sig||!token)return false;const a=[];for(const [k,v] of f.entries())a.push([k,String(v)]);a.sort((x,y)=>x[0]===y[0]?x[1].localeCompare(y[1]):x[0].localeCompare(y[0]));let p=req.url;for(const [k,v] of a)p+=k+v;const key=await crypto.subtle.importKey("raw",new TextEncoder().encode(token),{name:"HMAC",hash:"SHA-1"},false,["sign"]),d=await crypto.subtle.sign("HMAC",key,new TextEncoder().encode(p));return b64(d)===sig}
async function active(env,p,status="draft"){return env.DB.prepare("SELECT * FROM comics WHERE source_phone=? AND status=? ORDER BY updated_at DESC LIMIT 1").bind(p,status).first()}
async function count(env,id){const r=await env.DB.prepare("SELECT COUNT(*) n FROM comic_media WHERE comic_id=?").bind(id).first();return Number(r?.n||0)}
async function create(env,p,body){const id=crypto.randomUUID(),token=(crypto.randomUUID()+crypto.randomUUID()).replaceAll("-",""),w=words(body),t=now();await env.DB.prepare("INSERT INTO comics(id,preview_token,title,caption,status,source_phone,created_at,updated_at) VALUES(?,?,?,?,'draft',?,?,?)").bind(id,token,w.title,w.caption,p,t,t).run();return env.DB.prepare("SELECT * FROM comics WHERE id=?").bind(id).first()}
async function update(env,d,body){const w=words(body);await env.DB.prepare("UPDATE comics SET title=?,caption=?,updated_at=? WHERE id=?").bind(w.title,w.caption,now(),d.id).run();return w}
async function addMedia(env,f,d){let order=await count(env,d.id),n=parseInt(f.get("NumMedia")||"0",10);for(let i=0;i<n;i++){const url=String(f.get(`MediaUrl${i}`)||""),type=String(f.get(`MediaContentType${i}`)||"");if(!url||!type.startsWith("image/"))continue;const res=await fetch(url,{headers:{Authorization:`Basic ${btoa(env.TWILIO_ACCOUNT_SID+":"+env.TWILIO_AUTH_TOKEN)}`}});if(!res.ok)throw Error("media download failed");const data=await res.arrayBuffer();if(data.byteLength>12000000)throw Error("image too large");const key=`comics/${d.id}/${String(order).padStart(3,"0")}.${ext(type)}`;await env.MEDIA.put(key,data,{httpMetadata:{contentType:type}});await env.DB.prepare("INSERT INTO comic_media(id,comic_id,object_key,content_type,sort_order,alt_text,created_at) VALUES(?,?,?,?,?,'',?)").bind(crypto.randomUUID(),d.id,key,type,order,now()).run();order++}}
const origin=(env,r)=>String(env.PUBLIC_SITE_URL||new URL(r.url).origin).replace(/\/+$/,"");
export async function onRequestPost({request,env}){
 const need=["DB","MEDIA","ALLOWED_PHONE","TWILIO_ACCOUNT_SID","TWILIO_AUTH_TOKEN"].filter(x=>!env[x]);if(need.length)return reply("Publishing is not configured yet: "+need.join(", "),503);
 const f=await request.formData();if(!await signed(request,f,env.TWILIO_AUTH_TOKEN))return new Response("Bad signature",{status:403});
 const from=phone(f.get("From"));if(from!==phone(env.ALLOWED_PHONE))return new Response("Not authorized",{status:403});
 const body=String(f.get("Body")||"").trim(),cmd=body.toUpperCase(),commands=new Set(["DONE","PUBLISH","CHANGE","CANCEL","UNDO","HELP"]),num=parseInt(f.get("NumMedia")||"0",10);let d=await active(env,from);
 try{
  if(cmd==="HELP")return reply("Send comic pictures. Then text the title on the first line and caption underneath. Text DONE for preview, then PUBLISH. Commands: DONE, PUBLISH, CHANGE, CANCEL, UNDO, HELP.");
  if(cmd==="UNDO"){const c=await active(env,from,"published");if(!c)return reply("There is no published comic to undo.");await env.DB.prepare("UPDATE comics SET status='unpublished',updated_at=? WHERE id=?").bind(now(),c.id).run();return reply(`Unpublished "${c.title||"Untitled comic"}". Preview: ${origin(env,request)}/preview/${c.preview_token}. Reply PUBLISH to restore it.`)}
  if(num>0){if(!d)d=await create(env,from,commands.has(cmd)?"":body);else if(body&&!commands.has(cmd))await update(env,d,body);await addMedia(env,f,d);const n=await count(env,d.id);return reply(`Got ${n===1?"page 1":n+" pages"}. Send another picture, text the title and caption, or text DONE.`)}
  if(cmd==="CANCEL"){if(!d)return reply("There is no draft to cancel.");const m=await env.DB.prepare("SELECT object_key FROM comic_media WHERE comic_id=?").bind(d.id).all();for(const x of m.results||[])await env.MEDIA.delete(x.object_key);await env.DB.prepare("UPDATE comics SET status='cancelled',updated_at=? WHERE id=?").bind(now(),d.id).run();return reply("Draft cancelled. Nothing was published.")}
  if(cmd==="CHANGE")return reply(d?"Text the corrected title on the first line and caption underneath.":"There is no active draft.");
  if(cmd==="DONE"){if(!d)return reply("Send a comic picture first.");if(!await count(env,d.id))return reply("The draft has no pages.");return reply(`Private preview: ${origin(env,request)}/preview/${d.preview_token}. Reply PUBLISH when it looks right.`)}
  if(cmd==="PUBLISH"){if(!d)d=await active(env,from,"unpublished");if(!d)return reply("There is no draft to publish.");if(!await count(env,d.id))return reply("The draft has no pages.");const title=d.title.trim()||"Untitled comic",s=d.slug||`${slug(title)}-${d.id.slice(0,6)}`,t=now();await env.DB.prepare("UPDATE comics SET title=?,slug=?,status='published',published_at=?,updated_at=? WHERE id=?").bind(title,s,t,t,d.id).run();return reply(`Published: ${origin(env,request)}/comic/${s}. Text UNDO if it should come down.`)}
  if(body){if(!d)return reply("Send the first comic picture, then send the title and caption.");const w=await update(env,d,body);return reply(`Updated the title to "${w.title||"Untitled comic"}". Text DONE for preview.`)}
  return reply("Send a comic picture or text HELP.");
 }catch(e){console.error(e);return reply("I could not save that message. Nothing was published. Try again or text HELP.",500)}
}
export const onRequestGet=()=>new Response("POST only",{status:405,headers:{Allow:"POST"}});